### ISSUE TITLE
Unrouteable message due to normalization of keys

### ISSUE THREAD

**Issue by whd** [mozilla/gcp-ingestion#2609] opened 2024-06-21 20:02 UTC
/CC @akkomar 

Here's a stripped down ping demonstrating the failure. Basically, it appears that this ping passes schema validation treating `wr.framebuild_time` and `wr_framebuild_time` as both acceptable but then chokes when reconciling the two at a later step. If you remove one or the other this ping gets routed correctly.

This should probably be treated as an error since a client should not be sending one or the other of these.

```json
{
    "ping_info": {
        "seq": 0,
        "start_time": "2024-06-20T11:50+03:00",
        "end_time": "2024-06-21T10:41+03:00",
        "reason": "overdue"
    },
    "client_info": {
        "telemetry_sdk_build": "52.7.0",
        "app_display_version": "115.12.0",
        "app_channel": "esr",
        "app_build": "20240603145132",
        "architecture": "x86",
        "os": "Windows",
        "os_version": "6.1",
        "first_run_date": "2024-06-18+03:00",
        "build_date": "1970-01-01T00:00:00+00:00",
        "client_id": "e7ee6fd7-ec98-451e-b75e-f8443b46297a",
        "windows_build_number": 7600
    },
    "metrics": {
        "timing_distribution": {
            "wr.framebuild_time": {
                "values": {
                    "0": 0
                },
                "sum": 0
            },
            "wr_framebuild_time": {
                "values": {
                    "0": 0
                },
                "sum": 0
            }
        }
    }
}
```

```
extendedStackTrace: "java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:439) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:398) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:458) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:398) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:458) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:398) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.processField(PubsubMessageToObjectNode.java:458) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.transformForBqSchema(PubsubMessageToObjectNode.java:398) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.core.transform.PubsubMessageToObjectNode$Payload.apply(PubsubMessageToObjectNode.java:344) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$Ndjson$LazyEncodedInput.encode(Gcs.java:67) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$LazyEncodedInput.get(Gcs.java:116) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$Batch.getByteSize(Gcs.java:158) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.io.Gcs$Write$Batch.getByteSize(Gcs.java:122) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite$Batch.add(BatchWrite.java:210) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite.lambda$apply$3(BatchWrite.java:157) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1932) ~[?:?]
	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite.apply(BatchWrite.java:155) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.util.BatchWrite.apply(BatchWrite.java:26) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.config.SinkConfig$Output.apply(SinkConfig.java:162) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.mozilla.telemetry.ingestion.sink.config.SinkConfig$Output.apply(SinkConfig.java:136) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235) ~[?:?]
	at com.mozilla.telemetry.ingestion.sink.io.Pubsub.lambda$getConsumer$2(Pubsub.java:37) ~[ingestion-sink-0.1-SNAPSHOT.jar:?]
	at com.google.cloud.pubsub.v1.MessageDispatcher$3.run(MessageDispatcher.java:441) ~[google-cloud-pubsub-1.124.1.jar:1.124.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
"
localizedMessage: "class com.fasterxml.jackson.databind.node.ArrayNode cannot be cast to class com.fasterxml.jackson.databind.node.ObjectNode (com.fasterxml.jackson.databind.node.ArrayNode and com.fasterxml.jackson.databind.node.ObjectNode are in unnamed module of loader 'app')"
```

**Comment by akkomar** [comment] 2024-06-21 21:47
It seems correct that this ping passed validation and did not go into error stream, because generic JSON schemas used there do not contain per-probe fields.

In the sink one of these fields should have gone to `additional_properties`, but for some reason this is not happening. It probably should be `wr_framebuild_time` as `wr` is category of [this metric](https://dictionary.telemetry.mozilla.org/apps/firefox_desktop/metrics/wr_framebuild_time). We are doing some magic to replace dots with underscores in various places of the pipeline and this might be involved here.

I managed to run a unit test in https://github.com/mozilla/gcp-ingestion/compare/sink_poison?expand=1 with the stripped down payload from above that fails with the same error as in production. With a bit of debugging this should let us figure out what's going on. I'll continue looking into this next week.

**Comment by akkomar** [comment] 2024-06-24 16:59
I have a minimum unit test reproducing this issue in https://github.com/mozilla/gcp-ingestion/pull/2610/commits - first commit adds some new test inputs (passing) to validate how has the sink been working so far, second one adds a single input equivalent to the ping in question here (failing).

The reason is that we [normalize field names for BQ](https://github.com/mozilla/gcp-ingestion/blob/e1b318c84f189d979d75768097c51e6aaf97139a/ingestion-core/src/main/java/com/mozilla/telemetry/ingestion/core/transform/PubsubMessageToObjectNode.java#L782-L789) and transform JSON to a form compatible with BQ schema [in place while iterating over fields](https://github.com/mozilla/gcp-ingestion/blob/e1b318c84f189d979d75768097c51e6aaf97139a/ingestion-core/src/main/java/com/mozilla/telemetry/ingestion/core/transform/PubsubMessageToObjectNode.java#L370-L403).

This is happening only for map types and only when the "dot version" of the field precedes the "underscore version". This is because map structure is the only one that looks different in BQ schemas vs JSON schema. When we encounter the "dot version" of the field it is normalized, its value is transformed for BQ compatibility and inserted into "underscore version" in the processed JSON. Later on when we process the "underscore version" we hit `ClassCastException: ArrayNode -> ObjectNode`.

In the current implementation, if any other non-map field has a non-normalized equivalent(s) in the payload, the last non-normalized value ends up in the output message. We should ideally make maps work the same.
Although if implementation turns out to be too complicated I think we do not need to keep this behavior the same with respect to ordering. That's because [glean_parser does not allow dots in the metric name](https://github.com/mozilla/glean_parser/blob/a627c9704d7a472fec93c17053239cc2ead2a7e9/glean_parser/schemas/metrics.2-0-0.schema.yaml#L24), so such pings are erroneous submissions.

/cc @BenWu

**Comment by whd** [comment] 2024-06-24 17:36
> That's because [glean_parser does not allow dots in the metric name](https://github.com/mozilla/glean_parser/blob/a627c9704d7a472fec93c17053239cc2ead2a7e9/glean_parser/schemas/metrics.2-0-0.schema.yaml#L24), so such pings are erroneous submissions.

@akkomar and I are in agreement that this ping should be treated as an error so I'm dropping it from the production pipeline.

**Comment by BenWu** [comment] 2024-06-24 18:01
I might be misunderstanding what yo're saying, but isn't `wr.framebuild_time` the correct field in this case, not `wr_framebuild_time`?  The metric name doesn't allow `.` but in the json payload it should show up with the `.` as the separator between the category and name.

In any case, I agree that the it should be updated to handle this

**Comment by akkomar** [comment] 2024-06-24 18:28
> I might be misunderstanding what yo're saying, but isn't `wr.framebuild_time` the correct field in this case, not `wr_framebuild_time`? The metric name doesn't allow `.` but in the json payload it should show up with the `.` as the separator between the category and name.

I added a comment in https://github.com/mozilla/gcp-ingestion/pull/2610/files/749b2819368d6797c4171c42588c8ec865548b0d#r1651448014 which I hope adds some details.

Yes, `wr.framebuild_time` is the correct field in this case. However I think whatever we do here we should avoid encoding assumptions and rules to metric names in the sink.

**Comment by whd** [comment] 2024-08-08 21:38
Here's another example of a failure related to schema validation and normalization of keys, coming from a crash ping:

`"windowsUBRí":true`

I can provide a fuller ping example if we want to add a test case for this but the above should be sufficient to make a fake ping and reproduce the issue. The json schema is here: https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/telemetry/crash/crash.4.schema.json#L1372

So this value made it past validation and then produced the following normalized json:

`"windows_ubr":true`

which fails at BQ load time because `true` isn't a double.

**Comment by akkomar** [comment] 2024-08-14 14:16
> I can provide a fuller ping example if we want to add a test case for this but the above should be sufficient to make a fake ping and reproduce the issue. The json schema is here: https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/main/schemas/telemetry/crash/crash.4.schema.json#L1372

@whd can you provide a full example? I'm not able to reproduce this. Booleans seem to already be correctly coerced to numbers: https://github.com/mozilla/gcp-ingestion/blob/main/ingestion-core/src/test/resources/testdata/payload-format-input.ndjson#L2

**Comment by whd** [comment] 2024-08-14 14:54
Here's a mostly redacted crash ping. If it's not sufficient to reproduce I can look at pinpointing why:

```json
{
  "type": "crash",
  "id": "deadbeef-dead-beef-dead-deadbeefdead",
  "creationDate": "2024-08-08T18:34:30.000Z",
  "version": 4,
  "application": {
    "architecture": "x86-64",
    "buildId": "20240725162350",
    "name": "Firefox",
    "version": "128.0.3",
    "displayVersion": "128.0.3",
    "vendor": "Mozilla",
    "platformVersion": "128.0.3",
    "xpcomAbi": "x86_64-msvc",
    "channel": "release"
  },
  "payload": {
    "version": 1,
    "crashDate": "2024-08-04",
    "crashTime": "2024-08-04T08:00:00.000Z",
    "sessionId": "deadbeef-dead-beef-dead-deadbeefdead",
    "crashId": "deadbeef-dead-beef-dead-deadbeefdead",
    "minidumpSha256Hash": null,
    "processType": "main",
    "stackTraces": null,
    "metadata": {
      "BuildID": "20240624183754",
      "DOMFissionEnabled": "1",
      "GPUProcessLaunchCount": "1",
      "HeadlessMode": "0",
      "MozCrashReason": "out of memory: 0x0000000000140000 bytes requested",
      "OOMAllocationSize": "1310720",
      "ProductID": "{deadbeef-dead-beef-dead-deadbeefdead}",
      "ProductName": "Firefox",
      "ReleaseChannel": "release",
      "StartupCrash": "0",
      "Version": "127.0.2",
      "SystemMemoryUsePercentage": "94",
      "TotalVirtualMemory": "140737488224256",
      "AvailableVirtualMemory": "138521326821376",
      "TotalPhysicalMemory": "8502890496",
      "AvailablePhysicalMemory": "432406528",
      "TotalPageFile": "34272694272",
      "AvailablePageFile": "0",
      "CrashTime": "1722758407",
      "LastInteractionDuration": "127693",
      "UptimeTS": "21615543.03007",
      "SecondsSinceLastCrash": "50478189"
    },
    "hasCrashEnvironment": true
  },
  "clientId": "deadbeef-dead-beef-dead-deadbeefdead",
  "environment": {
    "build": {
      "applicationId": "{deadbeef-dead-beef-dead-deadbeefdead}",
      "applicationName": "Firefox",
      "architecture": "x86-64",
      "buildId": "20240624183754",
      "version": "127.0.2",
      "vendor": "Mozilla",
      "displayVersion": "127.0.2",
      "platformVersion": "127.0.2",
      "xpcomAbi": "x86_64-msvc",
      "updaterAvailable": true
    },
    "partner": {
      "distributionId": null,
      "distributionVersion": null,
      "partnerId": null,
      "distributor": null,
      "distributorChannel": null,
      "partnerNames": []
    },
    "system": {
      "memoryMB": 8109,
      "virtualMaxMB": 134217728,
      "cpu": {
        "isWindowsSMode": false,
        "count": 8,
        "cores": 4,
        "vendor": "GenuineIntel",
        "name": "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz",
        "family": 6,
        "model": 142,
        "stepping": 10,
        "l2cacheKB": 256,
        "l3cacheKB": 6144,
        "speedMHz": 1800,
        "extensions": [
          "hasMMX",
          "hasSSE",
          "hasSSE2",
          "hasSSE3",
          "hasSSSE3",
          "hasSSE4_1",
          "hasSSE4_2",
          "hasAVX",
          "hasAVX2",
          "hasAES"
        ]
      },
      "os": {
        "installYear": 2023,
        "hasSuperfetch": true,
        "hasPrefetch": true,
        "name": "Windows_NT",
        "version": "10.0",
        "locale": "en-US",
        "servicePackMajor": 0,
        "servicePackMinor": 0,
        "windowsBuildNumber": 22631,
        "windowsUBRí": true,
        "DWriteEnabled": true,
        "ContentBackend": "Skia",
        "Headless": false,
        "EmbeddedInFirefoxReality": false,
        "TargetFrameRate": 60,
        "adapters": [
          {
            "description": "Intel(R) UHD Graphics 620",
            "vendorID": "0x8086",
            "deviceID": "0x5917",
            "subsysID": "00261414",
            "RAM": 0,
            "driver": "driver",
            "driverVendor": null,
            "driverVersion": "27.20.100.8681",
            "driverDate": "9-5-2020",
            "GPUActive": true
          }
        ],
        "monitors": [
          {
            "screenWidth": 1024,
            "screenHeight": 768,
            "refreshRate": 60,
            "pseudoDisplay": false
          },
          {
            "screenWidth": 2736,
            "screenHeight": 1824,
            "refreshRate": 59,
            "pseudoDisplay": false
          }
        ],
        "features": {
          "compositor": "webrender",
          "hwCompositing": {
            "status": "available"
          },
          "gpuProcess": {
            "status": "available"
          },
          "webrender": {
            "status": "available"
          },
          "wrCompositor": {
            "status": "available"
          },
          "openglCompositing": {
            "status": "unused"
          },
          "omtp": {
            "status": "unused"
          },
          "d3d11": {
            "status": "available",
            "version": 45312,
            "warp": false,
            "textureSharing": true,
            "blocklisted": false
          },
          "d2d": {
            "status": "available",
            "version": "1.1"
          }
        }
      },
      "appleModelId": null,
      "hasWinPackageId": false,
      "sec": {
        "antivirus": [
          "Avast Antivirus"
        ],
        "antispyware": null,
        "firewall": [
          "Windows Firewall"
        ]
      },
      "isWow64": false,
      "isWowARM64": false
    },
    "settings": {
      "blocklistEnabled": true,
      "e10sEnabled": true,
      "e10sMultiProcesses": 8,
      "fissionEnabled": true,
      "telemetryEnabled": false,
      "locale": "en-US",
      "intl": {
        "requestedLocales": [
          "en-US"
        ],
        "availableLocales": [
          "en-US"
        ],
        "appLocales": [
          "en-US"
        ],
        "systemLocales": [
          "en-US"
        ],
        "regionalPrefsLocales": [
          "en-US"
        ],
        "acceptLanguages": [
          "en-US",
          "en"
        ]
      },
      "update": {
        "channel": "release",
        "enabled": true,
        "autoDownload": true,
        "background": true
      },
      "userPrefs": {
        "browser.search.region": "GU",
        "browser.search.widget.inNavBar": true,
        "browser.startup.homepage": "<user-set>",
        "browser.startup.page": 3,
        "browser.urlbar.autoFill": true,
        "browser.urlbar.autoFill.adaptiveHistory.enabled": false,
        "browser.urlbar.dnsResolveSingleWordsAfterSearch": 0,
        "browser.urlbar.quicksuggest.dataCollection.enabled": false,
        "browser.urlbar.showSearchSuggestionsFirst": false,
        "browser.urlbar.suggest.quicksuggest.nonsponsored": false,
        "browser.urlbar.suggest.quicksuggest.sponsored": false,
        "widget.content.gtk-high-contrast.enabled": true
      },
      "sandbox": {
        "effectiveContentProcessLevel": 6,
        "contentWin32kLockdownState": 15
      },
      "launcherProcessState": 0,
      "addonCompatibilityCheckEnabled": true,
      "isDefaultBrowser": false,
      "defaultSearchEngine": "google-b-d",
      "defaultSearchEngineData": {
        "loadPath": "[app]google@search.mozilla.org",
        "name": "Google",
        "origin": "default",
        "submissionURL": "https://www.google.com/search?client=firefox-b-d&q="
      }
    },
    "profile": {
      "creationDate": 19386,
      "firstUseDate": 19386
    },
    "addons": {
      "activeAddons": {
      },
      "theme": {
        "id": "default-theme@mozilla.org",
        "blocklisted": false,
        "description": "Follow the operating system setting for buttons, menus, and windows.",
        "name": "System theme — auto",
        "userDisabled": false,
        "appDisabled": false,
        "version": "1.3",
        "scope": 4,
        "foreignInstall": false,
        "hasBinaryComponents": false,
        "installDay": 19386,
        "updateDay": 19386
      },
      "activeGMPlugins": {
        "gmp-gmpopenh264": {
          "version": "2.3.2",
          "userDisabled": false,
          "applyBackgroundUpdates": 1
        },
        "gmp-widevinecdm": {
          "version": "4.10.2710.0",
          "userDisabled": false,
          "applyBackgroundUpdates": 1
        }
      }
    },
    "experiments": {
    },
    "services": {
      "accountEnabled": true,
      "syncEnabled": true
    }
  }
}
```

**Comment by akkomar** [comment] 2024-08-15 10:09
Thanks for the ping. Turns out I was checking conversion to integers, while here field type is float. It looks like we are not coercing booleans to floats, I have a test case demonstrating this in https://github.com/mozilla/gcp-ingestion/pull/2627/files

**Comment by akkomar** [comment] 2024-08-22 17:00
With https://github.com/mozilla/gcp-ingestion/pull/2627 and https://github.com/mozilla/gcp-ingestion/pull/2610 merged both issues identified here should be fixed.

**Closed by akkomar** 2024-08-22 17:00 UTC
